version: '3'

services:
  minecraft-server:
    build:
      context: ./minecraft-server
      args:
        JAR_URL: ${JAR_URL}
    image: minecraft-spigot/minecraft-server:${MINECRAFT_VER}
    command: ${XMS_SIZE} ${XMX_SIZE}
    ports:
      - ${HOST_PORT}:25565
    volumes:
      - ./minecraft-server/server-contents:/var/server-contents
